services:
  api:
    container_name: test_api
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["npm", "run", "start:dev"]
    tty: true
    ports:
      - ${HOST_PORT}:3000
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    ports:
      - ${HOST_DB_PORT}:3306
    healthcheck:
      test: "mysqladmin ping"
      interval: 10s
      retries: 10
    volumes:
      - ./backend/database:/var/lib/mysql

  migrate:
    container_name: sw3_mp_migrate
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["npm", "run", "migrate"]
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - migrate
